
services:
  entry:
    container_name: entry
    build:
      context: ./entry
      dockerfile: ./Dockerfile
    ports:
      - "2024:80"
    networks:
      - frontend
  
  webapp:
    build:
      context: ./tvsapp
      dockerfile: ./Dockerfile
    environment:
      - ELASTIC_URL=http://storage:9200
    networks:
      - frontend
      - backend

  storage:
    container_name: storage
    build:
      context: ./storage
      dockerfile: ./Dockerfile
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend

volumes:
  esdata:

networks:
  frontend:
  backend: